
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "grhvoclalziyjbjlhpml"

# The port that the API Gateway listens on. Defaults to 54321.
api_port = 54321

# The port that the Authentication server listens on. Defaults to 54322.
auth_port = 54322

# The port that the Realtime server listens on. Defaults to 54323.
realtime_port = 54323

# The port that the Studio listens on. Defaults to 54324.
studio_port = 54324

# Email testing server. Defaults to 54325.
inbucket_port = 54325

# The port that the DB listens on. Defaults to 54322.
db_port = 54322

# The port that the Edge Functions server listens on. Defaults to 54323.
functions_port = 54321

# The minimum log level to output. Defaults to "warn".
log_level = "warn"

# Enable/disable JWT verification for APIs and Functions. Defaults to true.
jwt_verification = true

# Configure database pooler option settings.
[pooler]
enabled = false
pool_mode = "transaction"
default_pool_size = 15
pool_size = 15

# Configure Edge Functions server options.
[functions]
# Function timeout in seconds. Defaults to 30.
function_timeout = 30
# Serve functions from the filesystem rather than the Database. Defaults to false.
serve_from_fs = false
# The maximum number of retries when a function fails. Defaults to 0.
max_retries = 1
# The delay between retries in milliseconds. Defaults to 0.
retry_interval = 500
# The port that the Edge Functions server listens on. Defaults to 54321.
serve_port = 54321
