
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grhvoclalziyjbjlhpml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyaHZvY2xhbHppeWpiamxocG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDY0NTUsImV4cCI6MjA1NzcyMjQ1NX0.cMxyK-VaP3gO5MwbPujoNj7dq6iPHdNBQ6a5kvvgPYA";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export the Supabase URL as a separate function
export const getSupabaseUrl = () => SUPABASE_URL;
